### ISSUE TITLE
Not Commiting Changes back to Sql Server Database

### ISSUE THREAD

**Issue by ZSBostonMA** [Pietervdw/SQLForExcel#3]
I'm using Excel 2016 32bit and SQL Server 2012.  When I change the data in excel, it is not writing the data back to the  SQL table when I click the green arrow.

**Comment by ranerajesh** [comment]
I see this same issue.

**Comment by aisbergde** [comment]
I can't commit anything back into SQL Server. SQL Servers are local or in Azure
