### ISSUE TITLE
Updates

### ISSUE THREAD

**Issue by Scullpa** [Pietervdw/SQLForExcel#6]
Hi Pieter-
I have to say we love your product!  You noted on the [](http://www.sqlforexcel.com/) site future updates such as additions and deletions.  Is that something you're still planning to add?  It's a feature we know we'd use on a regular basis if it was!

Thanks!
Rich

**Comment by Pietervdw** [comment]
Hi Rich,

Currently, I'm not actively developing this addin. I am a freelance developer and need to focus on work that generates income. Unfortunately this means that all my open source/ free projects are somewhat neglected at the moment.

I do however still plan on working further on this addin, but I cannot give any timelines on when.

Hope you understand.

Thank you.
--Pieter

**Comment by Scullpa** [comment]
Pieter-I certainly understand that.  Thank you for what you have previously created and thanks for letting me know.
Take care,Rich
